GET http://localhost:8080/api/posts

###

GET http://localhost:8080/api/posts/2

###

POST http://localhost:8080/api/posts
Content-Type: application/json

{
  "id": 0,
  "content": "THANKS MAXIM !!! Homework started, but I do not feel smarter)))"
}

###

PUT http://localhost:8080/api/posts
Content-Type: application/json

{
  "id": 2,
  "content": "PUT"
}

###

DELETE http://localhost:8080/api/posts/2


